site_name: 移动端生成工具使用文档
site_author: Roger
dev_addr: "192.168.1.232:8081"
nav:
  - 项目地址: index.md
  - 创建项目: create.md
  - 界面说明: intro.md
  - 功能安装: install.md
  - 生成项目: gen.md

theme:
  name: "material"
markdown_extensions:
  - smarty
  - toc:
      permalink: True
  - sane_lists
copyright: "version: 1.0"
